// Random C++ Code Generated by AI Codex
#include <iostream>
#include <string>
using namespace std;
int main() {
    string name = "AI Codex";
    cout << "Hello, my name is " << name << endl;
    return 0;
}
